name: animate_do
description: Beautiful animations inspired on Animate.css, every animation is a
  customizable widget.
version: 3.3.3
homepage: https://fernando-herrera.com
repository: https://github.com/Klerith/animate_do_package
issue_tracker: https://github.com/Klerith/animate_do_package/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

screenshots:
  - description: 'Animate_do example logo'
    path: screenshots/preview.gif
